[profile.default]
optimizer = true
optimizer_runs = 200
via_ir = true
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "solady/=lib/solady/src/"
]
[lint]
exclude_lints = ["asm-keccak256","mixed-case-function"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
